[[pairs]]
symbol = "BTCUSDC"
enabled = true
max_quote_notional = "850"
max_inventory_base = "0.010"
soft_inventory_base = "0.006"

[[pairs]]
symbol = "ETHUSDC"
enabled = true
max_quote_notional = "400"
max_inventory_base = "0.160"
soft_inventory_base = "0.090"
