[[pairs]]
symbol = "BTCUSDC"
enabled = true
max_quote_notional = "2000"
max_inventory_base = "0.030"
soft_inventory_base = "0.018"

[[pairs]]
symbol = "ETHUSDC"
enabled = true
max_quote_notional = "1000"
max_inventory_base = "0.500"
soft_inventory_base = "0.300"
